Updated debootstrap to 1.0.128+nmu2~bpo11+1

diff --git a/include/bootstrap/debian/debootstrap/debootstrap b/include/bootstrap/debian/debootstrap/debootstrap
--- a/include/bootstrap/debian/debootstrap/debootstrap
+++ b/include/bootstrap/debian/debootstrap/debootstrap
@@ -1,7 +1,7 @@
 #!/bin/sh
 set -e
 
-VERSION='1.0.114-meefik'
+VERSION='1.0.128+nmu2~bpo11+1'
 
 unset TMP TEMP TMPDIR || true
 
@@ -22,6 +22,7 @@ fi
 exec 4>&1
 
 LANG=C
+EXTRA_SUITES=""
 USE_COMPONENTS=main
 KEYRING=""
 DISABLE_KEYRING=""
@@ -40,14 +41,19 @@ EXTRACTOR_OVERRIDE=""
 UNPACK_TARBALL=""
 ADDITIONAL=""
 EXCLUDE=""
+EXCLUDE_DEPENDENCY=""
 VERBOSE=""
 CERTIFICATE=""
 CHECKCERTIF=""
 PRIVATEKEY=""
 CACHE_DIR=""
+INRELEASE_PATH=""
 
 DEF_MIRROR="http://deb.debian.org/debian"
 DEF_HTTPS_MIRROR="https://deb.debian.org/debian"
+
+# set $CONTAINER
+detect_container
 
 export LANG USE_COMPONENTS
 umask 022
@@ -96,6 +102,8 @@ usage()
 
       --include=A,B,C        adds specified names to the list of base packages
       --exclude=A,B,C        removes specified packages from the list
+      --extra-suites=A,B,C   also use packages from the listed suites of the
+                             archive
       --components=A,B,C     use packages from the listed components of the
                              archive
       --variant=X            use variant X of the bootstrap scripts
@@ -123,6 +131,10 @@ usage()
       --private-key=file     read the private key from file
       --certificate=file     use the client certificate stored in file (PEM)
       --no-check-certificate do not check certificate against certificate authorities
+
+      --inrelease-path       determine the path to the InRelease file of the main
+                             archive relative to the normal position of an InRelease
+                             file
 EOF
 }
 
@@ -305,6 +317,18 @@ if [ $# != 0 ] ; then
 		export VERBOSE
 		shift 1
 		;;
+	    --extra-suites|--extra-suites=?*)
+		if [ "$1" = "--extra-suites" ] && [ -n "$2" ]; then
+			EXTRA_SUITES="$2"
+			shift 2
+                elif [ "$1" != "${1#--extra-suites=}" ]; then
+			EXTRA_SUITES="${1#--extra-suites=}"
+			shift 1
+		else
+			error 1 NEEDARG "option requires an argument %s" "$1"
+		fi
+		EXTRA_SUITES="$(echo "$EXTRA_SUITES" | tr , " ")"
+		;;
 	    --components|--components=?*)
 		if [ "$1" = "--components" ] && [ -n "$2" ]; then
 			USE_COMPONENTS="$2"
@@ -384,10 +408,10 @@ if [ $# != 0 ] ; then
 			CERTIFICATE="--certificate=$2"
 			shift 2
 		elif [ "$1" != "${1#--certificate=}" ]; then
-			CERTIFICATE="--certificate=${1#--certificate=}"
+			CERTIFICATE="--certificate=${1#--certificate=}" 
 			shift 1
 		else
-		       error 1 NEEDARG "option requires an argument %s" "$1"
+		       error 1 NEEDARG "option requires an argument %s" "$1" 
 		fi
 		;;
 	    --private-key|--private-key=?*)
@@ -395,15 +419,26 @@ if [ $# != 0 ] ; then
 			PRIVATEKEY="--private-key=$2"
 			shift 2
 		elif [ "$1" != "${1#--private-key=}" ]; then
-			PRIVATEKEY="--private-key=${1#--private-key=}"
+			PRIVATEKEY="--private-key=${1#--private-key=}" 
 			shift 1
 		else
-		       error 1 NEEDARG "option requires an argument %s" "$1"
+		       error 1 NEEDARG "option requires an argument %s" "$1" 
 		fi
 		;;
 	    --no-check-certificate)
 		CHECKCERTIF="--no-check-certificate"
 		shift
+		;;
+		--inrelease-path|--inrelease-path=?*)
+		if [ "$1" = "--inrelease-path" ] && [ -n "$2" ]; then
+			INRELEASE_PATH="$2"
+			shift 2
+		elif [ "$1" != "${1#--inrelease-path=}" ]; then
+			INRELEASE_PATH=${1#--inrelease-path=}
+			shift 1
+		else
+			error 1 NEEDARG "option requires an argument %s" "$1"
+		fi
 		;;
 	    -*)
 		error 1 BADARG "unrecognized or invalid option %s" "$1"
@@ -419,7 +454,10 @@ fi
 # do auto proxy discovery
 AUTOPROXY=""
 if ! doing_variant fakechroot && command -v apt-config >/dev/null; then
-    eval "$(apt-config shell AUTOPROXY Acquire::http::ProxyAutoDetect)"
+    eval "$(apt-config shell AUTOPROXY Acquire::http::Proxy-Auto-Detect)"
+    if [ -z "$AUTOPROXY" ]; then
+        eval "$(apt-config shell AUTOPROXY Acquire::http::ProxyAutoDetect)"
+    fi
     if [ -z "$http_proxy" ] && [ -x "$AUTOPROXY" ]; then
         http_proxy="$($AUTOPROXY)"
         if [ -n "$http_proxy" ]; then
@@ -438,6 +476,9 @@ fi
 
 if [ "$SECOND_STAGE_ONLY" = "true" ]; then
 	SUITE=$(cat "$DEBOOTSTRAP_DIR/suite")
+	if [ -e "$DEBOOTSTRAP_DIR/extra-suites" ]; then
+		EXTRA_SUITES=$(cat "$DEBOOTSTRAP_DIR/extra-suites")
+	fi
 	ARCH=$(cat "$DEBOOTSTRAP_DIR/arch")
 	USER_MIRROR=$(cat "$DEBOOTSTRAP_DIR/mirror")
 	if [ -e "$DEBOOTSTRAP_DIR/variant" ]; then
@@ -558,7 +599,17 @@ if ! in_path "sha${SHA_SIZE}sum" && ! in_path "sha${SHA_SIZE}"; then
 fi
 DEBOOTSTRAP_CHECKSUM_FIELD="SHA$SHA_SIZE"
 
-export ARCH SUITE TARGET CHROOT_CMD SHA_SIZE DEBOOTSTRAP_CHECKSUM_FIELD
+export ARCH SUITE EXTRA_SUITES TARGET CHROOT_CMD SHA_SIZE DEBOOTSTRAP_CHECKSUM_FIELD
+
+if am_doing_phase first_stage second_stage; then
+	if in_path id && [ "$(id -u)" -ne 0 ]; then
+		error 1 NEEDROOT "debootstrap can only run as root"
+	fi
+	# Ensure that we can create working devices and executables on the target.
+	if ! check_sane_mount "$TARGET"; then
+		error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
+	fi
+fi
 
 if [ ! -e "$SCRIPT" ]; then
 	error 1 NOSCRIPT "No such script: %s" "$SCRIPT"
@@ -711,14 +762,15 @@ if am_doing_phase dldebs; then
 fi
 
 if am_doing_phase save_variables; then
-	cp "$DEBOOTSTRAP_DIR/debootstrap"				 "$TARGET/debootstrap/debootstrap"
+	cp "$0"				 "$TARGET/debootstrap/debootstrap"
 	cp "$DEBOOTSTRAP_DIR/functions"	 "$TARGET/debootstrap/functions"
 	cp "$SCRIPT"			 "$TARGET/debootstrap/suite-script"
 	# pick up common setting scripts
 	cp "$DEBOOTSTRAP_DIR"/scripts/*-common	"$TARGET/debootstrap/"
 	echo "$ARCH"			>"$TARGET/debootstrap/arch"
 	echo "$SUITE"			>"$TARGET/debootstrap/suite"
-	echo "$USER_MIRROR"		>"$TARGET/debootstrap/mirror"
+	[ "" = "$EXTRA_SUITES" ] ||
+	echo "$EXTRA_SUITES"		>"$TARGET/debootstrap/extra-suites"
 	[ "" = "$VARIANT" ] ||
 	echo "$VARIANT"			>"$TARGET/debootstrap/variant"
 	echo "$required"		>"$TARGET/debootstrap/required"
@@ -747,13 +799,15 @@ if am_doing_phase first_stage; then
 	first_stage_install
 
 	if ! am_doing_phase second_stage; then
-		cp "$DEBOOTSTRAP_DIR/debootstrap"				 "$TARGET/debootstrap/debootstrap"
+		cp "$0"				 "$TARGET/debootstrap/debootstrap"
 		cp "$DEBOOTSTRAP_DIR/functions"	 "$TARGET/debootstrap/functions"
 		cp "$SCRIPT"			 "$TARGET/debootstrap/suite-script"
 		# pick up common setting scripts
 		cp "$DEBOOTSTRAP_DIR"/scripts/*-common	"$TARGET/debootstrap/"
 		echo "$ARCH"			>"$TARGET/debootstrap/arch"
 		echo "$SUITE"			>"$TARGET/debootstrap/suite"
+		[ "" = "$EXTRA_SUITES" ] ||
+		echo "$EXTRA_SUITES"		>"$TARGET/debootstrap/extra-suites"
 		echo "$USER_MIRROR"		>"$TARGET/debootstrap/mirror"
 		[ "" = "$VARIANT" ] ||
 		echo "$VARIANT"			>"$TARGET/debootstrap/variant"
@@ -808,7 +862,7 @@ fi
 
 if am_doing_phase kill_target; then
 	if [ "$KEEP_DEBOOTSTRAP_DIR" != true ]; then
-		info KILLTARGET "Deleting target directory"
-		rm -rf "$TARGET"
+                info KILLTARGET "Deleting target directory"
+		rm -rf --one-file-system "$TARGET"
 	fi
 fi
